name: Latest Blog Posts

on:
  schedule:
    - cron: '0 */6 * * *' # 每 6 小時執行一次
  workflow_dispatch: # 允許手動觸發

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://agong.tech/index.xml"
          max_post_count: 5
          committer_username: "github-actions[bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Update blog posts"
          template: "- [$title]($url) - $date"
